//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stationery_store
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int Id_order { get; set; }
        public Nullable<System.DateTime> Date_order { get; set; }
        public Nullable<int> Order_cost { get; set; }
        public Nullable<bool> Paid { get; set; }
        public int Id_employees { get; set; }
        public int Id_delivery { get; set; }
        public int Id_customer { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Сustomer Сustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
